language: go
go:
  - 1.9

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

before_install:
- make dep-install
- go get -u github.com/golang/lint/golint

script:
  - make lint
  - golint -set_exit_status .
