language: go
go:
  - 1.9

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint

script:
  - dep ensure
  - go vet ./...
  - golint -set_exit_status .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "TODO: Build out GCP deployment"
    fi
