sudo: required

services:
  - docker
language: go
go:
  - 1.9.2

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

branches:
  only:
    - master

before_install:
  - make dep-install

script:
  - make lint

after_success:
  - make install_gcloud_sdk
