sudo: required

services:
  - docker
language: go
go:
  - 1.9.2

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_6e6de08e0ca3_key -iv $encrypted_6e6de08e0ca3_iv -in secrets.tar.enc -out ./secrets.tar -d
  - tar xvf secrets.tar
  - make dep-install

script:
  - make lint

after_success:
  - make install_gcloud_sdk
  - make gcloud_auth
